name: mugalimai
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Database
  postgres: ^2.6.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # Utils
  uuid: ^4.1.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Navigation
  go_router: ^12.1.3

  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  path_provider: ^2.1.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image & Camera
  image_picker: ^1.0.4
  camera: ^0.10.5+5

  # PDF
  pdf: ^3.10.7
  printing: ^5.11.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Animations
  animate_do: ^3.1.2
  shimmer: ^3.0.0

  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo-icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Localization
  generate: true


#  assets:
#    - assets/images
#    - assets/icons

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/shared/localization/arb
  output_dir: lib/shared/localization/generated
  use_deferred_loading: false